openapi: "3.1.0"
info:
  title: "Medieval API"
  description: "Medieval API"
  version: "1.0.0"
servers:
  - url: "http://localhost:8080"
paths:
  /api/nsi/update-all:
    post:
      summary: "Запрос на скачивание свежих справочников НСИ"
      operationId: "nsiUpdateAll"
      responses:
        "200":
          description: "OK - Нечего обновлять"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/SingleMessageDto"
        "201":
          description: "OK - Скачали новые версии"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/SingleMessageDto"
components:
  schemas:
    SingleMessageDto:
      type: "object"
      properties:
        message:
          type: "string"
          nullable: true
